May 29 Update
JiYouMCC/FlightRisingTool pull request #99
Opened 2018-05-29 15:41 UTC by LordZarcock

@JiYouMCC Updated with the new genes

2018-05-30 02:32 UTC, JiYouMCC commented on js/fr_data.js
> +    ['Firefly', 'Limited', 'Swipp'],
'Swipp' change to "Swipp's Swap Stand" is better.

2018-05-30 02:33 UTC, JiYouMCC commented on js/fr_data.js
> +    ['Python', 'Uncommon', 'Coli'],
'Coli' change to 'The Coliseum' is better. So does line 59

2018-05-30 02:34 UTC, JiYouMCC commented on lg/basic-zh.json
> +    "Python": "Python",
If convenient, you can change this line to

"Python": "蟒蛇 Python",

I can also do it after merge.

2018-05-30 02:35 UTC, JiYouMCC commented on lg/basic-zh.json
> +    "Firefly": "Firefly",
"Firefly": "萤火虫 Firefly",

2018-05-30 02:37 UTC, JiYouMCC commented on js/fr_data.js
> +    ['Morph', 'Uncommon', 'Coli'],
'Coli' change to 'The Coliseum' is better.

2018-05-30 02:38 UTC, JiYouMCC commented on lg/basic-zh.json
> +    "Filigree": "Filigree",
"Filigree": "掐丝 Filigree",

2018-05-30 02:39 UTC, JiYouMCC commented on lg/basic-zh.json
> +    "Morph": "Morph",
"Morph": "巨蟒 Morph",

2018-05-30 02:41 UTC, JiYouMCC requested changes
After change Coli and Swipp, I can approve this pull request. If you are convenient, you can change the chinese translate, or I can do it after merge.

2018-05-30 23:18 UTC, LordZarcock commented
@JiYouMCC changed Coli and Swipp, and added in the Chinese translations!

2018-05-31 04:29 UTC, merged

2018-05-31 04:29 UTC, JiYouMCC commented
@LordZarcock Thanks!